name: Build and deploy .NET Core Function App to cediscoveryinterop
on:
  push:
    branches:
    - master
env:
  AZURE_FUNCTIONAPP_NAME: cediscoveryinterop
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src\Microsoft.Azure.EventGrid.CloudEventsApis\published
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.CEDISCOVERYINTEROP_FFFF }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.x
  WORKING_DIRECTORY: src\Azure.CloudEvents.Discovery.Service
  DISCOVERY_DIRECTORY: src\Azure.CloudEvents.Discovery
  SCHEMA_DIRECTORY: src\Azure.CloudEvents.SchemaRegistry
  SUBSCRIPTIONS_DIRECTORY: src\Azure.CloudEvents.Subscriptions
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
      run: dotnet restore "${{ env.DISCOVERY_DIRECTORY }}"
      run: dotnet restore "${{ env.SCHEMA_DIRECTORY }}"
      run: dotnet restore "${{ env.SUBSCRIPTIONS_DIRECTORY }}"
    - name: Codegen NSwag
      run: dotnet build "${{ env.DISCOVERY_DIRECTORY }}" -target:NSwag --configuration ${{ env.CONFIGURATION }} --no-restore
      run: dotnet build "${{ env.SCHEMA_DIRECTORY }}" -target:NSwag --configuration ${{ env.CONFIGURATION }} --no-restore
      run: dotnet build "${{ env.SUBSCRIPTIONS_DIRECTORY }}" -target:NSwag --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
